version: 0.0
os: linux

files:
  - source: ./target/ROOT.war
    destination: /var/lib/tomcat7/webapps

hooks:
  AfterInstall:
    - location: ./codedeploy/restartTomcat.sh
      timeout: 180
      runas: ubuntu