#spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 12345678
  #jpa
  jpa:
    hibernate:
      ddl-auto: update