---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout # check out source code to working directory
      - run: 
          name: Gradle build
          command: |
            mvn --version
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Gradle build
          command: |
            java -jar 'target/webapp-0.0.1-SNAPSHOT.jar'



workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build-deploy-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master