---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:8.0.17
        environment:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: v1
          MYSQL_USER: user
          MYSQL_PASSWORD: 12345678
    steps:
      - checkout # check out source code to working directory
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root -p 12345678
#      - run:
#          name: Gradle build
#          command: |
#            mvn test
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Gradle build
          command: |
            mvn build



workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build-deploy-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master